[package]
name = "toka-storage"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Pluggable storage adapters for the Toka platform"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
walkdir = "2.5"

[dev-dependencies]
tempfile = "3.10" 