[package]
name = "toka-ledger"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Vault OS layer for Toka: causal event storage, intent clustering, and semantic embedding."

[dependencies]
# Core dependencies
serde = { version = "1.0", features = ["derive"] }
smallvec = { version = "1.13", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.7", features = ["v4", "serde"] }
anyhow = "1.0"
tokio = { workspace = true, features = ["full"] }

# Hashing and serialization helpers
blake3 = "1.5"
rmp-serde = "1.1"

# Intent clustering
ndarray = "0.15"
parking_lot = "0.12"

# Storage backend (pure Rust)
sled = "0.34"

[features]
default = []
# Enable for debugging/development
debug-intents = [] 