version: '3.8'

services:
  cursor-agent:
    build:
      context: .
      dockerfile: Dockerfile.cursor
    container_name: cursor-background-agent
    restart: unless-stopped
    # No external ports - cursor manages communication
    env_file:
      - .env.cursor
    environment:
      # Cursor-specific configuration
      - CURSOR_AGENT_MODE=true
      - RUST_LOG=${RUST_LOG:-warn}
      - RUST_BACKTRACE=${RUST_BACKTRACE:-0}
      - AGENT_DATA_DIR=/cursor/data
      - AGENT_LOG_DIR=/cursor/logs
      
      # Minimal resource usage for cursor agents
      - AGENT_POOL_SIZE=${AGENT_POOL_SIZE:-1}
      - AGENT_SPAWN_TIMEOUT=${AGENT_SPAWN_TIMEOUT:-10}
      - AGENT_WORKSTREAM_TIMEOUT=${AGENT_WORKSTREAM_TIMEOUT:-300}
      - CONTEXT_CACHE_SIZE=${CONTEXT_CACHE_SIZE:-128}
      - CONTEXT_CACHE_TTL=${CONTEXT_CACHE_TTL:-600}
      
      # Cursor LLM Configuration (minimal)
      - LLM_PROVIDER=${LLM_PROVIDER:-anthropic}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-claude-3-5-sonnet-20241022}
      - LLM_RATE_LIMIT=${LLM_RATE_LIMIT:-5}
      - LLM_TIMEOUT=${LLM_TIMEOUT:-30}
      - LLM_DEBUG=${LLM_DEBUG:-false}
    
    volumes:
      - cursor_data:/cursor/data
      - cursor_logs:/cursor/logs
      # Mount workspace for cursor agent access
      - .:/workspace:ro
    
    # No health checks - cursor manages lifecycle
    # No networking - cursor handles communication
    # No init system - cursor manages processes
    
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

volumes:
  cursor_data:
    driver: local
  cursor_logs:
    driver: local 