# Base Docker Compose configuration for Toka
# This file serves as a template and should be extended by environment-specific files
# Use docker-compose.dev.yml for development
# Use docker-compose.prod.yml for production
# Use docker-compose.cursor.yml for Cursor background agents

version: '3.8'

# This is a base configuration that should be extended
# See individual environment files for complete configurations:
# - docker-compose.dev.yml (development with debugging)
# - docker-compose.prod.yml (production with security)
# - docker-compose.cursor.yml (minimal for Cursor IDE)

services:
  # Base service definition - extend in environment-specific files
  toka-agents:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toka-background-agents
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - agent_data:/app/data
      - agent_logs:/app/logs
      - agent_config:/app/config
    networks:
      - toka-network

volumes:
  agent_data:
    driver: local
  agent_logs:
    driver: local
  agent_config:
    driver: local

networks:
  toka-network:
    driver: bridge 