[package]
name = "toka"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Top-level meta-crate that re-exports the most commonly used parts of the Toka platform."

[features]
# Enable all sub-crates by default for a batteries-included experience.
# Downstream users can cherry-pick (e.g. `default-features = false, features = ["auth"]`).
default = ["auth", "events", "agents", "toolkit"]

auth = ["dep:toka-capability"]
events = ["dep:toka-events"]
agents = ["dep:toka-agents"]
# toolkit feature exposes the default tools crate.
toolkit = ["dep:toka-toolkit-core", "dep:toka-tools"]

[dependencies]
# All dependencies are optional and tied to features above.
toka-capability     = { path = "../toka-capability", optional = true }
toka-events         = { path = "../toka-events",         optional = true }
toka-agents         = { path = "../toka-agents",         optional = true }
toka-tools          = { path = "../toka-tools",          optional = true }
toka-toolkit-core   = { path = "../toka-toolkit-core",   optional = true } 