[package]
name = "toka"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Top-level meta-crate that re-exports the most commonly used parts of the Toka platform."

[features]
# Enable all sub-crates by default for a batteries-included experience.
# Downstream users can cherry-pick (e.g. `default-features = false, features = ["auth"]`).
default = ["auth", "vault", "agents", "toolkit"]

auth = ["dep:toka-security-auth"]
vault = ["dep:toka-vault"]
agents = ["dep:toka-agents"]
# toolkit implies toolkit-core automatically via toka-toolkit's own deps.
toolkit = ["dep:toka-toolkit"]

[dependencies]
# All dependencies are optional and tied to features above.
toka-security-auth  = { path = "../toka-security-auth", optional = true }
toka-vault          = { path = "../toka-vault",          optional = true }
toka-agents         = { path = "../toka-agents",         optional = true }
toka-toolkit        = { path = "../toka-toolkit",        optional = true } 