[package]
name = "toka-kernel"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
toka-types = { path = "../toka-types" }
toka-auth = { path = "../toka-auth" }
toka-events = { path = "../toka-events" }
anyhow = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features=["sync","rt-multi-thread","macros"] }
async-trait = { workspace = true }
rand = { workspace = true }

[features]
default = []
# Opt-in families – keep the kernel pure by default.
finance = []
user = []
