[package]
name = "toka-memory"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
async-trait = "0.1"
anyhow = "1"
tokio = { version = "1", features = ["macros", "time", "sync", "rt"] } 