metadata:
  name: "build-validator"
  version: "1.0.0"
  category: "system"
  description: "Comprehensive build system validation for Rust workspace with dependency conflict detection"
  author: "Toka Development Team"
  created: "2025-07-06"

spec:
  executable:
    type: "shell"
    path: "system/validate-build-system.sh"
    interpreter: "bash"
    working_directory: "."
  
  capabilities:
    required:
      - "filesystem-read"
      - "process-spawn"
      - "cargo-execution"
    optional:
      - "filesystem-write"  # for validation reports
  
  security:
    level: "medium"
    sandbox:
      memory_limit: "1GB"
      cpu_limit: "75%"
      timeout: "30m"
      allow_network: true  # for cargo operations
      network_restrictions:
        - "crates.io"
        - "github.com"
      readonly_paths:
        - "Cargo.toml"
        - "crates"
        - "src"
      writable_paths:
        - "target"
        - "build_validation_reports"
  
  parameters:
    - name: "validation_phase"
      type: "enum"
      values: ["dependency", "individual", "workspace", "clippy", "docs", "full"]
      default: "full"
      description: "Validation phase to execute"
    - name: "verbose"
      type: "boolean"
      default: false
      description: "Enable verbose output"
    - name: "fail_fast"
      type: "boolean"
      default: false
      description: "Stop on first validation failure"

interface:
  discovery:
    auto_discover: true
    patterns:
      - "**/validate*build*.sh"
      - "**/build*validator*.sh"
  
  execution:
    hot_swappable: true
    parallel_safe: false  # Modifies shared workspace state
    resource_intensive: true
  
  integration:
    agent_types: ["build-system-stabilization", "development", "ci-cd"]
    runtime_events: ["workspace_change", "dependency_update"]
    compatible_backends: ["all"]
    
protocols:
  - type: "mcp"
    function_name: "validate_build_system"
    version: "1.0"
  - type: "a2a"
    action: "build_system.validation"

outputs:
  primary:
    - type: "report"
      formats: ["text", "json"]
      location: "build_validation_reports"
    - type: "validation_result"
      formats: ["json"]
      location: "build_validation_reports"
  
  metrics:
    - "validation_duration"
    - "phases_completed"
    - "errors_found"
    - "warnings_count"

dependencies:
  system:
    - "bash"
    - "cargo"
    - "rustc"
    - "git"
  workspace:
    - "Cargo.toml"
    - "crates/**/Cargo.toml" 