metadata:
  name: "date-validator"
  version: "1.0.0"
  category: "validation"
  description: "Enforces date accuracy and consistency across all workspace files"
  author: "Toka Development Team"
  created: "2025-07-06"

spec:
  executable:
    type: "python"
    path: "validation/validate_dates.py"
    interpreter: "python3"
    working_directory: "."
  
  capabilities:
    required:
      - "filesystem-read"
      - "date-validation"
      - "compliance-checking"
    optional:
      - "filesystem-write"  # for corrections
      - "git-access"  # for commit date sync
  
  security:
    level: "medium"
    sandbox:
      memory_limit: "256MB"
      cpu_limit: "25%"
      timeout: "5m"
      allow_network: false
      readonly_paths:
        - "**/*.md"
        - "**/*.rs"
        - "**/*.toml"
        - "**/*.yaml"
        - "**/*.yml"
      writable_paths:
        - "date_validation_reports"
  
  parameters:
    - name: "validation_mode"
      type: "enum"
      values: ["validate", "fix", "report"]
      default: "validate"
      description: "Mode of operation"
    - name: "file_patterns"
      type: "array"
      default: ["**/*.md", "**/*.rs", "**/*.toml", "**/*.yaml"]
      description: "File patterns to validate"
    - name: "strict_mode"
      type: "boolean"
      default: false
      description: "Enable strict date validation"
    - name: "verbose"
      type: "boolean"
      default: false
      description: "Enable verbose output"

interface:
  discovery:
    auto_discover: true
    patterns:
      - "**/validate*date*.py"
      - "**/date*validator*.py"
  
  execution:
    hot_swappable: true
    parallel_safe: true
    resource_intensive: false
  
  integration:
    agent_types: ["validation", "quality-assurance", "documentation"]
    runtime_events: ["file_change", "pre_commit"]
    compatible_backends: ["all"]
    
protocols:
  - type: "mcp"
    function_name: "validate_dates"
    version: "1.0"
  - type: "a2a"
    action: "quality_assurance.date_validation"

outputs:
  primary:
    - type: "validation_report"
      formats: ["text", "json"]
      location: "date_validation_reports"
    - type: "compliance_summary"
      formats: ["json"]
      location: "date_validation_reports"
  
  metrics:
    - "files_checked"
    - "errors_found"
    - "fixes_applied"
    - "compliance_score"

dependencies:
  system:
    - "python3"
    - "git"
  python:
    - "python-dateutil>=2.8.0"
  workspace:
    - "**/*.md"
    - "**/*.rs"
    - "**/*.toml"
    - "**/*.yaml" 