metadata:
  name: "date-template-processor"
  version: "1.0.0"
  category: "validation"
  description: "Processes date templates and inserts current dates in documentation"
  author: "Toka Development Team"
  created: "2025-07-06"

spec:
  executable:
    type: "shell"
    path: "validation/insert_date.sh"
    interpreter: "bash"
    working_directory: "."
  
  capabilities:
    required:
      - "filesystem-read"
      - "filesystem-write"
      - "template-processing"
    optional:
      - "git-access"  # for commit date sync
  
  security:
    level: "medium"
    sandbox:
      memory_limit: "128MB"
      cpu_limit: "10%"
      timeout: "2m"
      allow_network: false
      readonly_paths:
        - "**/*.md"
        - "**/*.rs"
        - "**/*.toml"
        - "**/*.yaml"
      writable_paths:
        - "**/*.md"  # Can modify markdown files
        - "template_processing_reports"
  
  parameters:
    - name: "mode"
      type: "enum"
      values: ["process", "preview", "validate"]
      default: "process"
      description: "Processing mode"
    - name: "pattern"
      type: "string"
      default: "**/*.md"
      description: "File pattern to process"
    - name: "template_format"
      type: "string"
      default: "{{DATE}}"
      description: "Template placeholder format"
    - name: "date_format"
      type: "string"
      default: "%Y-%m-%d"
      description: "Output date format"

interface:
  discovery:
    auto_discover: true
    patterns:
      - "**/insert*date*.sh"
      - "**/date*template*.sh"
  
  execution:
    hot_swappable: true
    parallel_safe: false  # Modifies files
    resource_intensive: false
  
  integration:
    agent_types: ["validation", "quality-assurance", "documentation"]
    runtime_events: ["template_update", "pre_commit"]
    compatible_backends: ["all"]
    
protocols:
  - type: "mcp"
    function_name: "process_date_templates"
    version: "1.0"
  - type: "a2a"
    action: "template_processing.date_insertion"

outputs:
  primary:
    - type: "processing_report"
      formats: ["text", "json"]
      location: "template_processing_reports"
    - type: "modified_files"
      formats: ["list"]
      location: "template_processing_reports"
  
  metrics:
    - "files_processed"
    - "templates_updated"
    - "processing_duration"

dependencies:
  system:
    - "bash"
    - "date"
    - "sed"
    - "grep"
  workspace:
    - "**/*.md"
    - "**/*.rs"
    - "**/*.toml"
    - "**/*.yaml" 