metadata:
  name: "dependency-visualizer"
  version: "1.0.0"
  category: "analysis"
  description: "Analyzes and visualizes dependency graphs for Rust workspace and agent compositions"
  author: "Toka Development Team"
  created: "2025-07-06"

spec:
  executable:
    type: "python"
    path: "analysis/dependency_graph_visualizer.py"
    interpreter: "python3"
    working_directory: "."
  
  capabilities:
    required:
      - "filesystem-read"
      - "workspace-analysis"
      - "visualization"
      - "process-spawn"
    optional:
      - "filesystem-write"
      - "git-access"
  
  security:
    level: "high"
    sandbox:
      memory_limit: "512MB"
      cpu_limit: "75%"
      timeout: "15m"
      allow_network: false
      readonly_paths:
        - "Cargo.toml"
        - "crates"
        - "config/agents.toml"
      writable_paths:
        - "dependency_graphs"
  
  parameters:
    - name: "analysis_type"
      type: "enum"
      values: ["workspace", "individual", "agents", "layered", "all"]
      default: "all"
      description: "Type of dependency analysis to perform"
    - name: "output_format"
      type: "enum"
      values: ["png", "svg", "both"]
      default: "both"
      description: "Output format for graphs"
    - name: "include_dev_deps"
      type: "boolean"
      default: false
      description: "Include development dependencies in analysis"
    - name: "output_dir"
      type: "string"
      default: "dependency_graphs"
      description: "Output directory for generated graphs"

interface:
  discovery:
    auto_discover: true
    patterns:
      - "**/dependency*visualizer*.py"
      - "**/dependency*graph*.py"
  
  execution:
    hot_swappable: true
    parallel_safe: false  # Accesses shared workspace files
    resource_intensive: true
  
  integration:
    agent_types: ["analysis", "development", "build-system-stabilization"]
    runtime_events: ["workspace_change", "cargo_update"]
    compatible_backends: ["all"]
    
protocols:
  - type: "mcp"
    function_name: "analyze_dependencies"
    version: "1.0"
  - type: "a2a"
    action: "workspace_analysis.dependencies"

outputs:
  primary:
    - type: "graph"
      formats: ["png", "svg"]
      location: "dependency_graphs"
    - type: "report"
      formats: ["markdown"]
      location: "dependency_graphs"
  
  metrics:
    - "analysis_duration"
    - "crates_analyzed"
    - "dependencies_found"
    - "graph_generation_time"

dependencies:
  system:
    - "python3"
    - "graphviz"
    - "git"
  python:
    - "toml>=0.10.2"
    - "graphviz>=0.20.1"
    - "aiofiles>=23.2.1"
    - "pyyaml>=6.0.1"
  workspace:
    - "Cargo.toml"
    - "crates/**/Cargo.toml" 