[package]
name = "toka-ledger-core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Minimal content-addressed event store: hashing + persistence + broadcast."

[dependencies]
serde = { version = "1.0", features = ["derive"] }
anyhow = "1"
smallvec = { version = "1.13", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
uuid  = { version = "1.7", features = ["v4", "serde"] }
blake3 = "1.5"
rmp-serde = "1.1"
sled = "0.34"
tokio = { workspace = true, features = ["sync", "time"] }
ndarray = "0.15" # kept for API parity, unused internally

[features]
default = [] 