[package]
name = "toka-storage-api"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ScrappyAI/toka"
authors = ["Toka Contributors <dev@toka.ai>"]
description = "Trait contracts for pluggable artefact storage in the Toka ecosystem. Compact, `no_std` compatible when default features disabled."

[dependencies]
anyhow = { version = "1.0", optional = true }
async-trait = { version = "0.1", optional = true }

[features]
default = ["async"]
async = ["dep:async-trait", "dep:anyhow"]