[package]
name = "toka-capability-jwt-hs256"
version = "0.2.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Concrete JWT HS256 implementation for Toka capability tokens"
authors = ["Toka Team <team@toka.dev>"]
repository = "https://github.com/toka-labs/toka"
keywords = ["jwt", "security", "capabilities", "tokens"]
categories = ["authentication", "cryptography"]

[dependencies]
repository = "https://github.com/scrappyAI/Toka"

toka-capability-core = { path = "../toka-capability-core" }

# Core dependencies
jsonwebtoken = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true, features = ["derive"] }
async-trait = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
tokio = { workspace = true, features = ["full"] }

[features]
# std feature by default. Disable for no_std use-case.
default = ["std"]
std = []
