[package]
name = "toka-capability"
version = "0.2.0-alpha"
edition = "2021"
license = "MIT OR Apache-2.0"
# Mark crate as deprecated for Cargo (cargo's convention)
[package.metadata]
deprecated = true

[dependencies]
# Re-export from new crate and core.
toka-capability-core = { path = "../toka-capability-core" }
toka-capability-jwt-hs256 = { path = "../toka-capability-jwt-hs256" }

[features]
# `legacy-v0_1` feature re-exports old API names if needed.
legacy-v0_1 = []