[package]
name = "toka-security-vault"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Secure encrypted key/value store for Toka runtime."

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sled = "0.34"
aes-gcm = "0.10"
rand = "0.8"
base64 = "0.21"

[dev-dependencies]
# Async runtime for integration tests
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
anyhow = "1"
rand = "0.8" 

[features]
# Default build includes all std deps. Lean builds can opt-in to `core` only.
default = ["core"]
core = [] 