[package]
name = "vault-intent"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Online intent clustering for Toka Vault OS events."

[dependencies]
ndarray = "0.15"
parking_lot = "0.12"
uuid = { version = "1.7", features = ["v4"] } 