[package]
name = "toka-ledger-finance"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Double-entry accounting helpers layered on top of toka-ledger."

[dependencies]
serde = { version = "1.0", features = ["derive"] }
anyhow = "1"
toka-primitives = { path = "../toka-primitives" }
serde_json = "1.0"
ndarray = "0.15"
toka-ledger = { path = "../toka-ledger" }

[features]
default = [] 