[package]
name = "toka-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
uuid = { version = "1", features = ["v4", "serde"] }
futures = "0.3"
dirs = "5.0"

# CLI / toolkit related crates (optional)
clap = { version = "4", features = ["derive"], optional = true }
typetag = { version = "0.2", optional = true }

# Toka ecosystem crates
toka-events = { path = "../toka-events", optional = true }
toka-tools = { path = "../toka-tools", optional = true }
toka-agents = { path = "../toka-agents", optional = true }
toka-security-auth = { path = "../toka-security-auth", optional = true }
toka-tools-api = { path = "../toka-tools-api", optional = true }
toka-bus = { path = "../toka-bus" }
toka-storage = { path = "../toka-storage" }

rmp-serde = { version = "1", optional = true }

rand = { workspace = true }
parking_lot = { version = "0.12", optional = true }

tracing-subscriber = { workspace = true }

[dev-dependencies]
tempfile = "3"
tokio-test = "0.4"

[features]
default = []
# enable full toolkit (cli + typetag + external crate)
toolkit = ["toka-tools", "clap", "typetag", "toka-agents", "toka-agents/toolkit", "toka-tools-api"]
# secure local event store
vault = ["dep:toka-events", "rmp-serde"]
# auth capability tokens utilities
auth = ["toka-security-auth", "parking_lot"]