[package]
name = "toka-runtime"
version = "0.2.1"
edition = "2021"
description = "Dynamic code execution runtime with kernel enforcement"
documentation = "https://docs.rs/toka-runtime"
repository = "https://github.com/user/Toka"
license = "MIT OR Apache-2.0"
keywords = ["runtime", "execution", "dynamic", "sandbox"]
categories = ["development-tools", "os"]

[dependencies]
# Kernel enforcement
toka-kernel = { path = "../toka-kernel" }
toka-types = { path = "../toka-types" }
toka-bus-core = { path = "../toka-bus-core" }

# Date/time handling
chrono = { workspace = true, features = ["serde"] }

# Core async runtime and utilities
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
thiserror = "1.0"
async-trait = "0.1"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Cryptography for code hashing
sha2 = "0.10"

# Logging
tracing = "0.1"

# WebAssembly execution (optional) - DISABLED FOR BLOAT REDUCTION
# wasmtime = { version = "20.0", optional = true }
# wasmtime-wasi = { version = "20.0", optional = true }

# Python execution (optional) - REMOVED FOR BLOAT REDUCTION
# pyo3 = { version = "0.21", features = ["auto-initialize"], optional = true }

# Process execution
tokio-process = "0.2"

# Templating for code generation
tera = { version = "1.19", optional = true }

[dev-dependencies]
tempfile = "3.0"
tokio-test = "0.4"

[features]
default = ["codegen"]  # Removed "wasm" and "python" for bloat reduction
# python = ["pyo3"]  # Disabled Python support
# wasm = ["wasmtime", "wasmtime-wasi"]  # Disabled WASM support
codegen = ["tera"]
# all-engines = ["wasm", "codegen"]  # Disabled "python" and "wasm"

