[package]
name = "toka-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
# newly added dependencies for core functionality
uuid = { version = "1", features = ["v4", "serde"] }
futures = "0.3"
# add unified events crate
toka-events = { path = "../toka-events" }
# crypto & utility crates used in auth/vault modules (kept optional for lean builds)
# sha2 = { version = "0.10", optional = true }
# hex = { version = "0.4", optional = true }
# base64 = { version = "0.21", optional = true }
# rand = { version = "0.8", optional = true }
# aes-gcm = { version = "0.10", optional = true }
# sled = { version = "0.34", optional = true }
# CLI / toolkit related crates (optional)
clap = { version = "4", features = ["derive"], optional = true }
typetag = { version = "0.2", optional = true }
# external crates
toka-toolkit = { path = "../toka-toolkit", optional = true }
toka-agents = { path = "../toka-agents", optional = true }
toka-security-auth = { path = "../toka-security-auth", optional = true }
toka-security-vault = { path = "../toka-security-vault", optional = true }
toka-toolkit-core = { path = "../toka-toolkit-core", optional = true }
toka-storage = { path = "../toka-storage" }
dirs = "5.0"

[dev-dependencies]
tempfile = "3"
tokio-test = "0.4"

[features]
default = []
# enable full toolkit (cli + typetag + external crate)
toolkit = ["toka-toolkit", "clap", "typetag", "toka-agents", "toka-agents/toolkit", "toka-toolkit-core"]
# secure local vault store
vault = ["toka-security-vault"]
# auth capability tokens utilities
auth = ["toka-security-auth"] 