[package]
name = "toka-runtime"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Runtime adapter for Toka OS - bridges deterministic kernel with storage and provides configuration management."

[dependencies]
# Core dependencies
toka-types = { path = "../toka-types" }
toka-auth = { path = "../toka-auth" }
toka-bus-core = { path = "../toka-bus-core" }
toka-kernel = { path = "../toka-kernel" }
toka-store-core = { path = "../toka-store-core" }

# Optional storage drivers
toka-store-memory = { path = "../toka-store-memory", optional = true }
toka-store-sled = { path = "../toka-store-sled", optional = true }

# Runtime dependencies
anyhow = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt", "time"] }
tracing = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "test-util"] }
uuid = { workspace = true, features = ["v4"] }
tempfile = "3.8"

[features]
default = ["memory-storage"]
memory-storage = ["dep:toka-store-memory"]
sled-storage = ["dep:toka-store-sled"]