[package]
name = "toka-performance"
version = "0.3.0"
edition = "2021"
description = "Performance monitoring and observability foundation for Toka OS"
authors = ["Toka OS Team"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/toka-io/toka-os"
documentation = "https://docs.rs/toka-performance"
keywords = ["performance", "monitoring", "observability", "metrics", "tracing"]
categories = ["development-tools::profiling", "development-tools::debugging"]

[dependencies]
# Core dependencies
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
tracing = "0.1"

# Metrics and monitoring (optional)
prometheus = { version = "0.13", features = ["process"], optional = true }
metrics = { version = "0.21", optional = true }
metrics-exporter-prometheus = { version = "0.12", optional = true }

# Distributed tracing (optional)
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"], optional = true }
tracing-opentelemetry = { version = "0.21", optional = true }
opentelemetry = { version = "0.21", optional = true }
opentelemetry-jaeger = { version = "0.20", optional = true }

# Performance analysis (optional)
criterion = { version = "0.5", optional = true }
pprof = { version = "0.12", features = ["flamegraph", "protobuf-codec"], optional = true }

# Dashboard and visualization (optional)
dashmap = { version = "5.0", optional = true }
parking_lot = { version = "0.12", optional = true }

# Random number generation for simulations
fastrand = "2.0"

# Internal dependencies
toka-types = { path = "../toka-types" }
toka-kernel = { path = "../toka-kernel" }

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.0"
criterion = "0.5"

[features]
default = ["metrics-collection", "distributed-tracing", "monitoring"]
metrics-collection = ["dep:prometheus", "dep:metrics", "dep:metrics-exporter-prometheus"]
distributed-tracing = ["dep:tracing-subscriber", "dep:tracing-opentelemetry", "dep:opentelemetry", "dep:opentelemetry-jaeger"]
monitoring = ["dep:dashmap", "dep:parking_lot"]
profiling = ["dep:pprof"]
benchmarking = ["dep:criterion"]
full = ["metrics-collection", "distributed-tracing", "monitoring", "profiling", "benchmarking"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]