[package]
name = "toka-store-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Core storage abstraction for Toka OS - event store traits and helpers without concrete implementations."

[dependencies]
# Minimal core dependencies only
toka-types = { path = "../toka-types" }
anyhow = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
blake3 = "1.5"
chrono = { version = "0.4", features = ["serde"] }
rmp-serde = "1.1"
smallvec = { version = "1.13", features = ["serde"] }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = "3.8"
tokio-test = "0.4"
tokio = { workspace = true, features = ["macros"] }

[features]
default = []