[package]
name = "toka-rule-metadata"
version = "0.1.0"
edition = "2021"
description = "Unified rule metadata catalogue and management system for Toka"
authors = ["Toka Team <team@toka.dev>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/scrappyAI/Toka"

[dependencies]
# Core dependencies
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
toml = "0.8"

# Date/time handling
chrono = { version = "0.4", features = ["serde"] }

# File system operations
walkdir = "2.0"
sha2 = "0.10"
hex = "0.4"

# Async runtime
tokio = { version = "1.0", features = ["full"] }

# Logging
tracing = "0.1"
tracing-subscriber = "0.3"

# CLI support
clap = { version = "4.0", features = ["derive"] }

# Toka dependencies
toka-types = { path = "../toka-types" }

[dev-dependencies]
tempfile = "3.0" 