[package]
name = "toka-testing"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Interactive testing environment for the Toka agentic operating system."

[[bin]]
name = "toka-test"
path = "src/main.rs"

[dependencies]
# Core Toka components
toka-runtime = { path = "../toka-runtime", features = ["memory-storage", "sled-storage", "sqlite-storage"] }
toka-auth = { path = "../toka-auth" }
toka-types = { path = "../toka-types" }

# CLI framework
clap = { workspace = true, features = ["derive"] }

# Async runtime and utilities
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal", "time"] }
anyhow = { workspace = true }

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

# Additional utilities
uuid = { workspace = true, features = ["v4"] }

# For interactive input
rustyline = "13.0"
colored = "2.0" 