[package]
name = "toka-memory-api"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Trait contracts for the pluggable key–value memory subsystem used across Toka services. Minimal, no_std friendly."
authors = ["Toka Contributors <dev@toka.ai>"]
repository = "https://github.com/ScrappyAI/toka"

[dependencies]
anyhow = { version = "1.0", optional = true }
async-trait = { version = "0.1", optional = true }

[features]
default = ["async"]
async = ["dep:async-trait", "dep:anyhow"]