[package]
name = "vault-bus"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Async event bus and storage layer for the Toka Vault OS."

[dependencies]
vault-core   = { path = "../vault-core",   version = "0.1.0" }
vault-hash   = { path = "../vault-hash",   version = "0.1.0" }
vault-intent = { path = "../vault-intent", version = "0.1.0" }

rocksdb = { version = "0.21", default-features = false, features = ["lz4"] }
serde   = { version = "1.0", features = ["derive"] }
rmp-serde = "1.1"
anyhow   = "1.0"
tokio    = { workspace = true, features = ["full"] } 