[package]
name = "minimal-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
env_logger = "0.10"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
toka-runtime = { path = "../../crates/toka-runtime", features = ["toolkit", "vault"] }
