[package]
name = "toka-toolkit-core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Tool trait and registry abstractions for the Toka platform (core crate)."

[dependencies]
anyhow = "1"
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["sync"] }
tracing = "0.1"
url = "2"
jsonschema = "0.17"

# Optional dependencies for advanced schema validation features
once_cell = { version = "1.19", optional = true }
dashmap = { version = "5.5", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
anyhow = "1"
async-trait = "0.1"

[features]
# Enables in-memory cache for compiled JSON Schemas to reduce validation cost.
schema_cache = ["once_cell", "dashmap"]

# Allows remote $ref resolution inside JSON Schemas (use with caution).
allow_remote_refs = [] 