[package]
name = "toka-toolkit-core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Minimal tool trait + registry abstractions for Toka."

[dependencies]
anyhow = "1"
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["sync"] }
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
anyhow = "1"
async-trait = "0.1" 