[package]
name = "toka-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1"
# needed by several tools; keep core parts optional via features
tokio = { version = "1", features = ["macros", "rt-multi-thread", "fs", "sync", "io-util"], optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", optional = true }
serde_cbor = { version = "0.11", optional = true }
csv = { version = "1.3", optional = true }
chrono = { version = "0.4", features = ["serde", "clock"], optional = true }
uuid = { version = "1", features = ["v4", "serde"], optional = true }
futures = { version = "0.3", optional = true }
rand = { version = "0.8", optional = true }
hex = { version = "0.4", optional = true }
sha2 = { version = "0.10", optional = true }
base64 = { version = "0.21", optional = true }
tracing = { version = "0.1" }
typetag = { version = "0.2", optional = true }
toka-toolkit-core = { path = "../toka-toolkit-core" }

[dev-dependencies]
# Async test runtime and utilities
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time", "fs", "io-util"] }
anyhow = "1"
rand = "0.8"
serde_cbor = "0.11"
tempfile = "3.10"

[features]
# Phase-0: clean slate – only the `echo` demo tool.
echo = []
minimal = ["echo"]
default = ["minimal"]
