[package]
name = "toka-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "fs", "sync", "io-util"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_cbor = "0.11"
csv = "1.3"
chrono = { version = "0.4", features = ["serde", "clock"] }
uuid = { version = "1", features = ["v4", "serde"] }
futures = "0.3"
rand = "0.8"
hex = "0.4"
sha2 = "0.10"
base64 = "0.21"
directories = "5.0"
tracing = "0.1"
typetag = "0.2"
toka-tools-api = { path = "../toka-tools-api" }

[dev-dependencies]
# Async test runtime and utilities
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time", "fs", "io-util"] }
anyhow = "1"
rand = "0.8"
serde_cbor = "0.11"
tempfile = "3.10"
