[package]
name = "toka-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1"
# Needed by the core registry & most tools – now non-optional to silence lints
tokio = { version = "1", features = ["macros", "rt-multi-thread", "fs", "sync", "io-util"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_cbor = { version = "0.11", optional = true }
csv = { version = "1.3", optional = true }
chrono = { version = "0.4", features = ["serde", "clock"], optional = true }
uuid = { version = "1", features = ["v4", "serde"], optional = true }
futures = { version = "0.3", optional = true }
rand = { version = "0.8", optional = true }
hex = { version = "0.4", optional = true }
sha2 = { version = "0.10", optional = true }
base64 = { version = "0.22", optional = true }
tracing = { version = "0.1" }
typetag = { version = "0.2", optional = true }
# new deps from former toolkit-core
url = "2"
jsonschema = "0.17"
once_cell = { version = "1.19", optional = true }
dashmap = { version = "5.5", optional = true }
wasmtime = { version = "11", optional = true, features = ["wat"] }
reqwest = { version = "0.11", optional = true, default-features = false, features = ["json", "rustls-tls"] }

[dev-dependencies]
# Async test runtime and utilities
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time", "fs", "io-util", "process"] }
anyhow = "1"
rand = "0.8"
serde_cbor = "0.11"
tempfile = "3.10"
proptest = "1.4"
tokio-test = { workspace = true }
futures = { workspace = true }
# Dependencies for examples
tracing-subscriber = "0.3"

[features]
# Phase-0: clean slate – only the `echo` demo tool.
echo = []
minimal = ["echo"]

# External tool integration features
external-tools = ["tokio/process"]

# additional features ported from toolkit-core
schema_cache = ["once_cell", "dashmap"]
allow_remote_refs = []
wasm_loader = ["wasmtime"]
http_transport = ["reqwest"]

default = ["minimal", "external-tools"]

[[example]]
name = "agent_tool_integration"
required-features = ["external-tools"]
