[package]
name = "toka-store-sled"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Sled-based persistent storage driver for Toka OS - durable, embedded event storage."

[dependencies]
toka-store-core = { path = "../toka-store-core" }
anyhow = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
sled = "0.34"
rmp-serde = "1.1"

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
uuid = { workspace = true, features = ["v4"] }
serde = { workspace = true, features = ["derive"] }
tempfile = "3.8"