[package]
name = "toka-vault"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Canonical, secure, and persistent event store for the Toka platform. The single source of truth for 'what happened'."
repository = "https://github.com/ScrappyAI/toka"
keywords = ["vault", "event-sourcing", "storage", "sled", "ledger"]

[dependencies]
# Core
anyhow = "1.0"
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.10", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
smallvec = { version = "1.13", features = ["serde"] }
blake3 = "1.5"
tokio = { workspace = true, features = ["sync", "time"] }
rmp-serde = "1.1"

# For sled persistence backend
sled = { version = "0.34", optional = true }

# For intent clustering
ndarray = { version = "0.15", optional = true }
parking_lot = { version = "0.12", optional = true }
smart-embedder = { path = "../smart-embedder", optional = true }


[dev-dependencies]
tempfile = "3.8"
tokio-test = "0.4"


[features]
default = ["persist-sled", "memory-vault"]

# Enables the sled-backed persistent vault implementation
persist-sled = ["dep:sled"]

# Enables the in-memory (non-persistent) vault for testing
memory-vault = []

# Enables online intent clustering using embeddings.
# NOTE: This requires the C++ LibTorch library to be installed on the system
# if the `transformers` feature of `smart-embedder` is also enabled.
intent-cluster = ["dep:ndarray", "dep:parking_lot", "dep:smart-embedder"]