[package]
name = "toka-types"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
anyhow = "1"
async-trait = "0.1"

[dev-dependencies]
serde_json = { workspace = true }
