[package]
name = "toka-rate-limiter"
version = "0.2.1"
edition = "2021"
license = "Apache-2.0"
description = "Authentication rate limiting middleware for Toka security framework"

[dependencies]
keywords = ["rate-limiting", "security", "middleware", "algorithms", "policies"]
categories = ["security", "algorithms"]
repository = "https://github.com/scrappyAI/Toka"

serde = { workspace = true, features = ["derive"] }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["time", "sync"] }
chrono = { workspace = true, features = ["serde"] }
uuid = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
toka-capability-core = { path = "../toka-capability-core" }

[dev-dependencies]
tokio-test = { workspace = true }

[features]
default = ["std"]
std = [] 
