metadata:
  name: "build-validator"
  version: "1.0.0"
  category: "validation"
  description: "Validates build system integrity and dependencies"

spec:
  executable:
    type: "rust"
    entry_point: "build_validator"
  
  capabilities:
    required:
      - "filesystem-read"
      - "process-execution"
      - "validation"
    optional:
      - "network-access"
  
  security:
    level: "medium"
    sandbox:
      memory_limit: "256MB"
      cpu_limit: "50%"
      timeout: "2m"
      allow_network: true
      readonly_paths:
        - "/workspace"
  
  parameters:
    - name: "workspace_path"
      type: "string"
      description: "Path to workspace root"
      required: true
    - name: "check_dependencies"
      type: "boolean"
      description: "Whether to validate dependencies"
      default: true
    - name: "fix_issues"
      type: "boolean"
      description: "Whether to auto-fix issues"
      default: false

interface:
  discovery:
    auto_discover: true
  
  execution:
    hot_swappable: true
    parallel_safe: false
    
protocols:
  - type: "rust_native"
    function_name: "validate_build"
    version: "1.0" 