metadata:
  name: "date-validator"
  version: "1.0.0"
  category: "validation"
  description: "Validates dates in workspace files to prevent future dates"

spec:
  executable:
    type: "rust"
    entry_point: "date_validator"
  
  capabilities:
    required:
      - "filesystem-read"
      - "validation"
    optional:
      - "filesystem-write"
  
  security:
    level: "medium"
    sandbox:
      memory_limit: "128MB"
      cpu_limit: "25%"
      timeout: "30s"
      allow_network: false
      readonly_paths:
        - "/workspace"
  
  parameters:
    - name: "path"
      type: "string"
      description: "Path to validate (file or directory)"
      required: true
    - name: "fix_violations"
      type: "boolean"
      description: "Whether to fix date violations"
      default: false
    - name: "strict_mode"
      type: "boolean"
      description: "Strict validation mode"
      default: true

interface:
  discovery:
    auto_discover: true
  
  execution:
    hot_swappable: true
    parallel_safe: true
    
protocols:
  - type: "rust_native"
    function_name: "validate_dates"
    version: "1.0" 