[package]
name = "toka-secrets"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Encrypted secrets vault for Toka platform"

[dependencies]
aes-gcm = "0.10"
# async support helpers
async-trait = "0.1"
anyhow = "1"
base64 = "0.21"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sled = "0.34"
futures = "0.3"
tokio = { version = "1", optional = true } # only if used? ignore for now
toka-storage = { path = "../toka-storage" }

[dev-dependencies]
# Async runtime for integration tests
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
anyhow = "1"
rand = "0.8"
futures = "0.3"
tempfile = "3"

[features]
# Default build includes all std deps. Lean builds can opt-in to `core` only.
default = ["core"]
core = [] 