name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-nextest (fast test runner)
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - name: Format check
        run: cargo fmt --all -- --check
      - name: Lint (clippy, deny warnings)
        run: cargo clippy --workspace --all-features -- -D warnings
      - name: Build (all features)
        run: cargo check --workspace --all-features
      - name: Build lean runtime (no default features)
        run: cargo check -p toka-runtime --no-default-features
      - name: Run tests
        run: cargo nextest run --workspace 