name: Workstream CI
on:
  push:
    branches: 
      - "feature/build-system-stabilization"
      - "feature/testing-infrastructure" 
      - "feature/kernel-events-expansion"
      - "feature/storage-enhancements"
      - "feature/security-enhancements"
      - "feature/performance-observability"
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # Determine which workstream is being tested
  detect-workstream:
    runs-on: ubuntu-latest
    outputs:
      workstream: ${{ steps.detect.outputs.workstream }}
      branch: ${{ steps.detect.outputs.branch }}
    steps:
      - name: Detect workstream from branch
        id: detect
        run: |
          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
          
          case "$BRANCH_NAME" in
            "feature/build-system-stabilization")
              echo "workstream=build-system" >> $GITHUB_OUTPUT
              ;;
            "feature/testing-infrastructure")
              echo "workstream=testing" >> $GITHUB_OUTPUT
              ;;
            "feature/kernel-events-expansion")
              echo "workstream=kernel-events" >> $GITHUB_OUTPUT
              ;;
            "feature/storage-enhancements")
              echo "workstream=storage" >> $GITHUB_OUTPUT
              ;;
            "feature/security-enhancements")
              echo "workstream=security" >> $GITHUB_OUTPUT
              ;;
            "feature/performance-observability")
              echo "workstream=performance" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "workstream=unknown" >> $GITHUB_OUTPUT
              echo "⚠️ Unknown workstream detected: $BRANCH_NAME"
              ;;
          esac
          
          echo "✅ Detected workstream: $(cat $GITHUB_OUTPUT | grep workstream | cut -d'=' -f2)"

  # Basic validation for all workstreams
  basic-validation:
    runs-on: ubuntu-latest
    needs: detect-workstream
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Format check
        run: cargo fmt --all -- --check
      
      - name: Basic build check
        run: cargo check --workspace --all-features
      
      - name: Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
      
      - name: Basic tests
        run: cargo test --workspace --all-features

  # Agent configuration validation (required by all branch protection rules)
  agent-config-validation:
    runs-on: ubuntu-latest
    needs: detect-workstream
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Validate agent configurations
        run: |
          echo "🔍 Validating agent configurations..."
          
          # Check if agent configuration files exist and are valid
          if [ -d "agents/v0.3.0/workstreams" ]; then
            echo "✅ Agent workstream directory found"
            
            # Validate YAML files
            for config_file in agents/v0.3.0/workstreams/*.yaml; do
              if [ -f "$config_file" ]; then
                echo "  - Validating $(basename "$config_file")"
                # Basic YAML validation using Python
                python3 -c "
import yaml
import sys
try:
    with open('$config_file', 'r') as f:
        yaml.safe_load(f)
    print('    ✅ Valid YAML')
except Exception as e:
    print(f'    ❌ Invalid YAML: {e}')
    sys.exit(1)
"
              fi
            done
          else
            echo "⚠️ Agent workstream directory not found"
          fi
          
          # Validate agent configuration matches current workstream
          workstream="${{ needs.detect-workstream.outputs.workstream }}"
          if [ "$workstream" != "unknown" ]; then
            echo "🎯 Validating configuration for workstream: $workstream"
            # Add specific validation logic here if needed
          fi
          
          echo "✅ Agent configuration validation completed"

  # Documentation validation (required by some branch protection rules)
  docs-validation:
    runs-on: ubuntu-latest
    needs: detect-workstream
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate documentation
        run: |
          echo "📚 Validating documentation..."
          
          # Check for required documentation files
          required_docs=(
            "README.md"
            "docs/proposals/"
            "agents/v0.3.0/README.md"
          )
          
          for doc in "${required_docs[@]}"; do
            if [ -e "$doc" ]; then
              echo "  ✅ Found: $doc"
            else
              echo "  ⚠️ Missing: $doc"
            fi
          done
          
          # Check for broken links in markdown files (basic check)
          echo "🔗 Checking for basic markdown syntax issues..."
          find . -name "*.md" -type f | while read -r file; do
            if grep -q "]()" "$file"; then
              echo "  ⚠️ Found empty link in $file"
            fi
          done
          
          echo "✅ Documentation validation completed"

  # Fallback validation for unknown workstreams
  unknown-workstream-validation:
    if: needs.detect-workstream.outputs.workstream == 'unknown'
    runs-on: ubuntu-latest
    needs: [detect-workstream, basic-validation]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Extended validation for unknown workstream
        run: |
          echo "🔍 Running extended validation for unknown workstream"
          
          # Run comprehensive tests
          cargo test --workspace --all-features --verbose
          
          # Check for any new crates that might need testing
          echo "📦 Checking for new crates..."
          for crate_dir in crates/*/; do
            if [ -f "$crate_dir/Cargo.toml" ]; then
              crate_name=$(basename "$crate_dir")
              echo "  - Found crate: $crate_name"
              cargo check -p "$crate_name" --all-features
            fi
          done
          
          # Run security-related checks
          echo "🔒 Running security validation..."
          cargo test -p toka-auth --all-features
          
          echo "✅ Unknown workstream validation completed"

  # Build System Workstream Validation
  build-system-validation:
    if: needs.detect-workstream.outputs.workstream == 'build-system'
    runs-on: ubuntu-latest
    needs: [detect-workstream, basic-validation]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Run build system validation script
        run: |
          chmod +x scripts/validate-build-system.sh
          ./scripts/validate-build-system.sh
      
      - name: Dependency conflict detection
        run: |
          cargo tree --duplicates || echo "No duplicate dependencies found"
          
      - name: Edition2024 compatibility check
        run: |
          # Check for base64 compatibility specifically
          if cargo check -p toka-tools --all-features; then
            echo "✅ Base64 compatibility verified"
          else
            echo "❌ Base64 compatibility issues detected"
            exit 1
          fi

  # Testing Infrastructure Workstream Validation  
  testing-validation:
    if: needs.detect-workstream.outputs.workstream == 'testing'
    runs-on: ubuntu-latest
    needs: [detect-workstream, basic-validation]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Install testing tools
        run: |
          echo "📦 Installing testing tools..."
          
          # Install cargo-nextest with better error handling
          if ! command -v cargo-nextest >/dev/null 2>&1; then
            echo "Installing cargo-nextest..."
            if ! cargo install cargo-nextest --locked; then
              echo "⚠️ cargo-nextest installation failed, will use standard cargo test"
            fi
          else
            echo "✅ cargo-nextest already available"
          fi
          
          # Install cargo-llvm-cov with better error handling
          if ! command -v cargo-llvm-cov >/dev/null 2>&1; then
            echo "Installing cargo-llvm-cov..."
            if ! cargo install cargo-llvm-cov --locked; then
              echo "⚠️ cargo-llvm-cov installation failed, will skip coverage"
            fi
          else
            echo "✅ cargo-llvm-cov already available"
          fi
      
      - name: Run integration tests
        run: |
          echo "🧪 Running integration tests..."
          if command -v cargo-nextest >/dev/null 2>&1; then
            echo "Using cargo-nextest for faster testing"
            cargo nextest run --workspace --all-features
          else
            echo "Using standard cargo test"
            cargo test --workspace --all-features
          fi
      
      - name: Generate coverage report
        run: |
          echo "📊 Generating coverage report..."
          if command -v cargo-llvm-cov >/dev/null 2>&1; then
            cargo llvm-cov --workspace --all-features --summary-only
          else
            echo "⚠️ Coverage tool not available, skipping coverage report"
          fi

  # Kernel Events Workstream Validation
  kernel-events-validation:
    if: needs.detect-workstream.outputs.workstream == 'kernel-events'
    runs-on: ubuntu-latest
    needs: [detect-workstream, basic-validation]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Validate kernel modifications
        run: |
          # Test kernel crate specifically
          cargo test -p toka-kernel --all-features
      
      - name: Event schema validation
        run: |
          # Validate event definitions don't break existing schemas
          cargo check -p toka-kernel --all-features
          echo "Event schema validation passed"

  # Storage Workstream Validation
  storage-validation:
    if: needs.detect-workstream.outputs.workstream == 'storage'
    runs-on: ubuntu-latest
    needs: [detect-workstream, basic-validation]
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: toka_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Test storage backends
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/toka_test
        run: |
          # Test storage crates with different backends
          cargo test -p toka-store-core --all-features
          cargo test -p toka-store-memory --all-features
          cargo test -p toka-store-sled --all-features
          cargo test -p toka-store-sqlite --all-features
      
      - name: Storage integration tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/toka_test  
        run: |
          # Test storage integration across different backends
          cargo test --workspace --all-features -- storage

  # Security Workstream Validation
  security-validation:
    if: needs.detect-workstream.outputs.workstream == 'security'
    runs-on: ubuntu-latest
    needs: [detect-workstream, basic-validation]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Security audit
        run: |
          echo "🔍 Running security audit..."
          
          # Install cargo-audit with better error handling
          if ! command -v cargo-audit >/dev/null 2>&1; then
            echo "Installing cargo-audit..."
            if ! cargo install cargo-audit --locked; then
              echo "⚠️ cargo-audit installation failed, will skip security audit"
              exit 0
            fi
          else
            echo "✅ cargo-audit already available"
          fi
          
          # Run security audit
          if command -v cargo-audit >/dev/null 2>&1; then
            cargo audit
          else
            echo "⚠️ Cargo audit not available, skipping security audit"
          fi
      
      - name: Test security features
        run: |
          # Test auth and security crates
          cargo test -p toka-auth --all-features
          cargo test -p toka-capability-core --all-features
          cargo test -p toka-capability-jwt-hs256 --all-features
          cargo test -p toka-revocation --all-features
          cargo test -p toka-cvm --all-features

  # Performance Workstream Validation
  performance-validation:
    if: needs.detect-workstream.outputs.workstream == 'performance'
    runs-on: ubuntu-latest
    needs: [detect-workstream, basic-validation]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Install benchmarking tools
        run: |
          cargo install cargo-criterion --locked || true
      
      - name: Run performance tests
        run: |
          # Run any existing benchmarks
          if [ -d "benches" ]; then
            cargo bench --workspace || echo "No benchmarks found"
          else
            echo "Benchmark directory not found, skipping"
          fi
      
      - name: Performance regression check
        run: |
          # Placeholder for performance regression detection
          echo "Performance baseline validation - implement based on specific metrics"

  # Agent configuration validation
  agent-config-validation:
    runs-on: ubuntu-latest
    needs: detect-workstream
    steps:
      - uses: actions/checkout@v4
      
      - name: Install YAML validation tools
        run: |
          pip install yamllint
      
      - name: Validate agent configurations
        run: |
          # Validate all agent YAML configs
          find agents/v0.3.0/workstreams -name "*.yaml" -exec yamllint {} \;
      
      - name: Check agent config completeness
        run: |
          # Verify agent config has required fields
          for config in agents/v0.3.0/workstreams/*.yaml; do
            echo "Validating $(basename "$config")..."
            # Add validation logic here based on your config schema
          done

  # Documentation validation
  docs-validation:
    runs-on: ubuntu-latest
    needs: basic-validation
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Build documentation
        run: |
          cargo doc --workspace --no-deps --all-features
      
      - name: Test doc examples
        run: |
          cargo test --doc --workspace --all-features

  # Final validation summary
  validation-summary:
    runs-on: ubuntu-latest
    needs: [
      detect-workstream,
      basic-validation,
      agent-config-validation,
      docs-validation
    ]
    if: always()
    steps:
      - name: Report validation results
        run: |
          echo "=== Workstream CI Validation Summary ==="
          echo "Workstream: ${{ needs.detect-workstream.outputs.workstream }}"
          echo "Branch: ${{ needs.detect-workstream.outputs.branch }}"
          echo "Basic validation: ${{ needs.basic-validation.result }}"
          echo "Agent config validation: ${{ needs.agent-config-validation.result }}"
          echo "Documentation validation: ${{ needs.docs-validation.result }}"
          
          if [[ "${{ needs.basic-validation.result }}" == "success" && \
                "${{ needs.agent-config-validation.result }}" == "success" && \
                "${{ needs.docs-validation.result }}" == "success" ]]; then
            echo "✅ All validations passed"
          else
            echo "❌ Some validations failed"
            exit 1
          fi 