[package]
name = "toka-key-rotation"
version = "0.2.1"
edition = "2021"
license = "Apache-2.0"
description = "Automatic JWT key rotation and management for Toka capability tokens"

[dependencies]
serde = { workspace = true, features = ["derive"] }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["time", "sync"] }
chrono = { workspace = true, features = ["serde"] }
uuid = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
rand = { workspace = true }
hex = "0.4"
serde_json = { workspace = true }
jsonwebtoken = { workspace = true }
toka-capability-core = { path = "../toka-capability-core" }

[dev-dependencies]
tokio-test = { workspace = true }

[features]
default = ["std"]
std = [] 